<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'>
<meta name='applicable-device' content='pc'><meta name='keywords' content='电脑,电脑讲解,电脑技术,编程,电脑故障维修AutoCAD ObjectARX 二次开发（2020版）--4,使用ARX向导创建CAD二次开发项目（编程框架）--' />
<script src='../../highlight/highlight.pack.js'></script>
<link rel='stylesheet' type='text/css' href='../../highlight/styles/monokai.css'/>

<link rel='stylesheet' href='../../fenxiang/dist/css/share.min.css'>
<script src='../../fenxiang/src/js/social-share.js'></script>
<script src='../../fenxiang/src/js/qrcode.js'></script>

</head><body><script>hljs.initHighlightingOnLoad();</script><script>
var system ={};  
var p = navigator.platform;       
system.win = p.indexOf('Win') == 0;  
system.mac = p.indexOf('Mac') == 0;  
system.x11 = (p == 'X11') || (p.indexOf('Linux') == 0);     
if(system.win||system.mac||system.xll){
document.write("<link href='../css/3.css' rel='stylesheet' type='text/css'>");}else{ document.write("<link href='../css/3wap.css' rel='stylesheet' type='text/css'>");}</script><script src='../../js/3.js'></script><div class='div2'><div class='heading_nav'><ul><div><li><a href='../../index.html'>首页</a></li>
</div><div onclick='hidden1()' >分享</div>
</ul></div></div>
<div id='heading_nav2'> 
<li class='row' >
<div class='social-share' data-mode='prepend'><a href='javascript:' class='social-share-icon icon-heart'></a></div></li></div><script charset='utf-8' src='../../3/js/hengfu.js'></script><script charset='utf-8' src='../../3/js/hengfu2.js'></script><hr><div class='div1'><div class='biaoti'><center>AutoCAD ObjectARX 二次开发（2020版）--4,使用ARX向导创建CAD二次开发项目（编程框架）--</center></div><div class='banquan'>原文出处:本文由博客园博主高渐离-Cloud提供。<br/>
原文连接:https://www.cnblogs.com/F_Shadow/p/11995966.html</div><br>
    <p><span>手动创建ObjectARX应用程序非常麻烦，</span><span>在此步骤中，将介绍ObjectARX向导。</span></p>
<p><span>在这里，我们将使用ObjectARX向导创建我们的ObjectARX应用程序。</span></p>
<p><span>本节的程序的需求是，接收CAD用户的输入。</span></p>
<p>首先，打开VS2017，新建项目</p>
<p>在左边的树形目录里依次选择 Visual&nbsp; C++&nbsp; &nbsp; --&gt;&nbsp; Autodesk</p>
<p>然后在窗口中间选择 ARX/DBX Project For AutoCAD 2020</p>
<p>点击确定</p>
<p><img src="./images/AutoCAD ObjectARX 二次开发（2020版）--4,使用ARX向导创建CAD二次开发项目（编程框架）--0.png" alt="" width="605" height="419" /></p>
<p>&nbsp;</p>
<p>这里可能遇到一些状况导致点击确定后无法进入下一步，</p>
<p>有可能是本教程开头介绍的部件没有完全安装，或者安装过程中路径选择错误，或者安装向导的时候没有使用管理员权限导致的。</p>
<p>如果前面的准备工作一切就绪，那么确定后会弹出这样的窗口来</p>
<p><img src="./images/AutoCAD ObjectARX 二次开发（2020版）--4,使用ARX向导创建CAD二次开发项目（编程框架）--1.png" alt="" width="501" height="399" /></p>
<p>窗口第一行可输入的内容是注册开发人员符号（RDS），</p>
<p>如果你有的话，就输入你的符号，</p>
<p>如果你不知道这是什么的话，请忽略，这个不影响我们开发程序，只是个标识符。</p>
<p>其它选项我们暂时不需要，可以直接点击完成（Finish）。</p>
<p>当你看到这个场景的时候，恭喜你，编程模板（框架）已经准备好了，我们要写自己的业务和逻辑进去了。</p>
<p><img src="./images/AutoCAD ObjectARX 二次开发（2020版）--4,使用ARX向导创建CAD二次开发项目（编程框架）--2.png" alt="" width="835" height="452" /></p>
<p>&nbsp;</p>
<p>因为ARX开发的方式是，将自己的函数注册给库，指定调用命令就完成了。</p>
<p>CAD加载我们的程序后，用你事先指定的命令，就可以调用对应的函数了。</p>
<p>重点来了，在创建我们自己的函数之前，我们先学习模板里预留给我们的函数。</p>
<p>在acrxEntryPoint.cpp 77行左右，你应该能看到这个函数</p>
<div class="cnblogs_Highlighter">
<pre><code>	static void ADSKMyGroupMyCommand () {
		// Put your command code here
	}</pre>
</div>
<p>这就是一个可以被注册为CAD指令的函数。</p>
<p>函数名其实是两部分组成的，前半段为ADSKMyGroup，后半段为MyCommand。</p>
<p>前半段的意义类似于名字空间，默认是你的RDS符号+MyGroup,实际上可以是任何合法的字符</p>
<p>后半段才是真正的函数名，是你想给函数取的名字。</p>
<p>比如你可以取一个函数名为 static void CloudTestInput(){ }</p>
<p>请注意，修辞是static，返回值是void，参数为空，都是固定的，不能变。</p>
<p>虽然现在函数内部是空的，没有关系，最后一步再来写函数内容，先看文件最下面，找到这一句</p>
<div class="cnblogs_Highlighter">
<pre><code>ACED_ARXCOMMAND_ENTRY_AUTO(CArxProject1App, ADSKMyGroup, MyCommand, MyCommandLocal, ACRX_CMD_MODAL, NULL)
</pre>
</div>
<p>这是将函数注册为CAD指令的方法。</p>
<p>一共有6个参数。</p>
<p>参数1：程序标识符，使用默认值</p>
<p>参数2：注册函数的前半段名字，也就是刚才说的名字空间</p>
<p>参数3：注册函数的后半段名字，真正意义的函数名</p>
<p>参数3：CAD指令。这是你创建的CAD指令，当在CAD中输入这条指令时就会调用对应的函数。</p>
<p>参数4：模式，暂时使用默认值。</p>
<p>参数5：默认NULL</p>
<p>&nbsp;</p>
<p>生成程序，会得到一个后缀为ARX的文件，这就是我们的CAD插件。不过现在这个插件没有任何功能。</p>
<p>我们现在来写函数内容，让这个插件拥有接收用户输入的功能。</p>
<p>注意，ARX要求生成过程中0警告0错误，哪怕有一个警告也会阻止生成成功。</p>
<p>所以，拿出强迫症精神，做ARX开发，一个警告都不能有。</p>
<p>&nbsp;</p>
<p>我们给刚才的函数内部添加如下内容：</p>
<div class="cnblogs_Highlighter">
<pre><code>	static void ADSKMyGroupMyCommand() {

		wchar_t temp[32];
		wmemset(temp, 0, 32);

		acutPrintf(_T("这是我的第一个ARX插件\n"));		//输出
		acedGetString(0,_T("请问你的名字是："),temp);	//输入
		acutPrintf(_T("你好，%s\n"),temp);		//输出
	}
</pre>
</div>
<p>　　</p>
<p>简介一下acedGetString函数，这是接受输入的函数，有很多重载方式，当前使用的方式有三个参数。</p>
<p>参数1：若为0，空格和回车都会使字符串输入结束，若非0，空格不会使字符串输入结束，需要回车才会结束。</p>
<p>参数2：输出字符串的部分</p>
<p>参数3，接收字符串的缓存</p>
<p>&nbsp;</p>
<p>生成新的ARX吧，然后依照第三节的内容加载ARX并且执行这条指令。</p>
<p>指令是你自己创建的，本例中为&nbsp;MyCommandLocal。</p>
<p>执行效果如下：</p>
<p><img src="./images/AutoCAD ObjectARX 二次开发（2020版）--4,使用ARX向导创建CAD二次开发项目（编程框架）--3.png" alt="" /></p>
<p>&nbsp;</p>
<p>你可以依照上面的格式，自己在acrxEntryPoint.cpp文件的类中添加新的函数</p>
<p>然后添加一条新的注册指令。</p>
<p>就像这样</p>
<div class="cnblogs_Highlighter">
<pre><code>	static void BIMCloudHello() {

		wchar_t temp[32];
		wmemset(temp, 0, 32);

		acutPrintf(_T("这是我的第一个ARX插件\n"));		//输出
		acedGetString(0,_T("请问你的名字是："),temp);	//输入
		acutPrintf(_T("你好，%s\n"),temp);			//输出
	}



ACED_ARXCOMMAND_ENTRY_AUTO(CArxProject1App, BIMCloud, Hello, myhello, ACRX_CMD_MODAL, NULL)
</pre>
</div>
<p>　　</p>
<p>然后在CAD中执行myhello指令，就可以调用这个函数了。记得，新函数要添加在acrxEntryPoint文件的类当中，作为一个类成员函数。</p>
<p>&nbsp;</p>
<p>你应该已经注意到，整个过程中没有添加任何头文件，</p>
<p>因为创建模板的时候，ARX向导已经帮我们添加好了，所以非常方便，直接就可以写业务逻辑了。</p>
<p>但是你用到Unicode字符的话，就需要自己添加</p>
<p><span style="color: #0000ff;">#include</span>&nbsp;"tchar.h"</p>
</div>
</div><hr><script charset='utf-8' src='../../js/sming.js'></script></body></html>